import React,{useMemo,useState}from'react';
import Swal from'sweetalert2';
import{Search,ShieldCheck,Users,UserCheck,UserRoundCog,X,Save,UserPlus,UserX,RotateCcw,History,DatabaseBackup}from'lucide-react';

const blank={prefix:'',name:'',position:'',department:'',personnelType:'',email:'',role:'USER',status:'PENDING'};

export default function AdminCenter({data,onSave,onCreate,onSetActive,onAudit,onBackup,busy}){
 const[q,setQ]=useState(''),[editing,setEditing]=useState(null),[creating,setCreating]=useState(false),[draft,setDraft]=useState(blank);
 const rows=useMemo(()=>{const s=q.trim().toLowerCase();return(data?.people||[]).filter(p=>!s||`${p.personId} ${p.name} ${p.email} ${p.position} ${p.department}`.toLowerCase().includes(s))},[data,q]);
 const sum=data?.summary||{};
 const toggle=async p=>{const active=p.status!=='ACTIVE';const r=await Swal.fire({icon:active?'question':'warning',title:active?'เปิดใช้งานบัญชีนี้อีกครั้ง?':'ระงับบัญชีนี้?',html:active?`<b>${p.name}</b> จะกลับมาเข้าสู่ระบบได้`:`<b>${p.name}</b> จะเข้าสู่ระบบไม่ได้ แต่ข้อมูลและประวัติจะยังอยู่ครบ`,showCancelButton:true,confirmButtonText:active?'เปิดใช้งาน':'ระงับบัญชี',cancelButtonText:'ยกเลิก',confirmButtonColor:active?'#168a5c':'#c53d3d'});if(r.isConfirmed)await onSetActive({personId:p.personId,active})};
 return <section className="admin-center">
  <div className="admin-hero"><div><small>ADMIN CONTROL CENTER</small><h2>ศูนย์ผู้ดูแลระบบ</h2><p>บริหารบัญชี สิทธิ์ และความครบถ้วนของบุคลากรในที่เดียว</p></div><div className="admin-hero-actions"><button onClick={onAudit}><History/>AuditLog</button><button onClick={onBackup}><DatabaseBackup/>สำรองข้อมูล</button><span><ShieldCheck/>สิทธิ์ผู้ดูแลได้รับการยืนยัน</span></div></div>
  <div className="admin-stats"><Stat icon={<Users/>} label="บุคลากรทั้งหมด" value={sum.total||0}/><Stat icon={<UserCheck/>} label="เปิดใช้งาน" value={sum.active||0}/><Stat icon={<ShieldCheck/>} label="ผู้ดูแลระบบ" value={sum.admins||0}/><Stat icon={<UserRoundCog/>} label="ข้อมูลยังไม่ครบ" value={sum.incomplete||0}/></div>
  <div className="panel admin-list"><div className="admin-list-head"><div><h2>จัดการบัญชีบุคลากร</h2><p>เพิ่ม แก้ไข ระงับ และเปิดคืนได้ โดยไม่ลบประวัติ</p></div><div className="admin-head-actions"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหาชื่อ รหัส อีเมล หรือตำแหน่ง"/></label><button className="admin-add" onClick={()=>{setDraft(blank);setCreating(true)}}><UserPlus/>เพิ่มบุคลากร</button></div></div>
   <div className="admin-table"><div className="admin-row admin-th"><span>บุคลากร</span><span>อีเมล</span><span>บทบาท</span><span>สถานะ</span><span>ข้อมูล</span><span>จัดการ</span></div>{rows.map(p=><div className="admin-row" key={p.personId}><span className="admin-person">{p.photoUrl?<img src={p.photoUrl}/>:<i>{(p.name||'ผ').charAt(0)}</i>}<b>{p.name}<small>{p.personId} · {p.position||'รอข้อมูล'}</small></b></span><span className={p.email?'':'muted'}>{p.email||'ยังไม่ผูกอีเมล'}</span><span><Badge type={p.role}>{roleLabel(p.role)}</Badge></span><span><Badge type={p.status}>{statusLabel(p.status)}</Badge></span><span className={p.dataStatus==='ข้อมูลครบถ้วน'?'ok-text':'warn-text'}>{p.dataStatus||'รอตรวจสอบ'}</span><span className="admin-row-actions"><button className="admin-edit" onClick={()=>setEditing({...p})}>แก้ไข</button><button disabled={busy} className={p.status==='ACTIVE'?'admin-archive':'admin-restore'} onClick={()=>toggle(p)}>{p.status==='ACTIVE'?<><UserX/>ระงับ</>:<><RotateCcw/>เปิดคืน</>}</button></span></div>)}{!rows.length&&<div className="admin-empty">ไม่พบบุคลากรที่ค้นหา</div>}</div>
  </div>
  {creating&&<div className="back admin-back"><form className="admin-modal admin-create" onSubmit={e=>{e.preventDefault();onCreate(draft).then(()=>setCreating(false))}}><button type="button" className="x" onClick={()=>setCreating(false)}><X/></button><UserPlus className="big"/><h2>เพิ่มบุคลากรใหม่</h2><p>ระบบจะสร้างรหัสบุคลากรและบัญชีให้อัตโนมัติ</p><div className="formgrid"><label>คำนำหน้า/สมณศักดิ์<input value={draft.prefix} onChange={e=>setDraft(v=>({...v,prefix:e.target.value}))}/></label><label>ชื่อ-ฉายา/นามสกุล<input required value={draft.name} onChange={e=>setDraft(v=>({...v,name:e.target.value}))}/></label></div><div className="formgrid"><label>ตำแหน่ง<input value={draft.position} onChange={e=>setDraft(v=>({...v,position:e.target.value}))}/></label><label>ฝ่ายงาน<input value={draft.department} onChange={e=>setDraft(v=>({...v,department:e.target.value}))}/></label></div><div className="formgrid"><label>ประเภทบุคลากร<input value={draft.personnelType} onChange={e=>setDraft(v=>({...v,personnelType:e.target.value}))}/></label><label>อีเมล Google<input type="email" value={draft.email} onChange={e=>setDraft(v=>({...v,email:e.target.value}))} placeholder="เว้นไว้ได้หากยังไม่มี"/></label></div><div className="formgrid"><label>บทบาท<select value={draft.role} onChange={e=>setDraft(v=>({...v,role:e.target.value}))}><option value="USER">บุคลากร</option><option value="REVIEWER">กรรมการ</option><option value="ADMIN">ผู้ดูแลระบบ</option></select></label><label>สถานะ<select value={draft.status} onChange={e=>setDraft(v=>({...v,status:e.target.value}))}><option value="PENDING">รอเปิดใช้งาน</option><option value="ACTIVE">เปิดใช้งาน</option><option value="INACTIVE">ระงับใช้งาน</option></select></label></div><button disabled={busy} className="primary submit"><UserPlus/>{busy?'กำลังเพิ่ม…':'เพิ่มบุคลากรและสร้างบัญชี'}</button></form></div>}
  {editing&&<div className="back admin-back"><form className="admin-modal" onSubmit={e=>{e.preventDefault();onSave({personId:editing.personId,email:editing.email,role:editing.role,status:editing.status}).then(()=>setEditing(null))}}><button type="button" className="x" onClick={()=>setEditing(null)}><X/></button><UserRoundCog className="big"/><h2>จัดการบัญชีบุคลากร</h2><p>{editing.name} · {editing.personId}</p><label>อีเมล Google<input type="email" value={editing.email||''} onChange={e=>setEditing(v=>({...v,email:e.target.value}))} placeholder="name@gmail.com"/></label><div className="formgrid"><label>บทบาท<select value={editing.role||'USER'} onChange={e=>setEditing(v=>({...v,role:e.target.value}))}><option value="USER">บุคลากร</option><option value="REVIEWER">กรรมการ</option><option value="ADMIN">ผู้ดูแลระบบ</option><option value="SUPER_ADMIN">ผู้ดูแลสูงสุด</option></select></label><label>สถานะ<select value={editing.status||'PENDING'} onChange={e=>setEditing(v=>({...v,status:e.target.value}))}><option value="ACTIVE">เปิดใช้งาน</option><option value="PENDING">รอเปิดใช้งาน</option><option value="INACTIVE">ระงับใช้งาน</option></select></label></div><button disabled={busy} className="primary submit"><Save/>{busy?'กำลังบันทึก…':'บันทึกสิทธิ์และบัญชี'}</button></form></div>}
 </section>
}
function Stat({icon,label,value}){return <article>{icon}<p><small>{label}</small><b>{value}</b></p></article>}
function Badge({type,children}){return <em className={`admin-badge ${String(type||'').toLowerCase()}`}>{children}</em>}
function roleLabel(x){return({USER:'บุคลากร',REVIEWER:'กรรมการ',ADMIN:'ผู้ดูแล',SUPER_ADMIN:'ผู้ดูแลสูงสุด'})[x]||x}
function statusLabel(x){return({ACTIVE:'เปิดใช้งาน',PENDING:'รอเปิด',INACTIVE:'ระงับ'})[x]||x}
