import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{LayoutDashboard,FolderOpen,ClipboardCheck,FileText,Users,BarChart3,Settings,Search,Plus,Share2,Bell,CheckCircle2,Clock3,BookOpen,FlaskConical,Handshake,Landmark,Sparkles,Upload,Menu,X,LogIn,LogOut,UserRound,Save,ShieldCheck,KeyRound,MonitorCog,Database,HardDrive,Eye,RefreshCw}from'lucide-react';
import Swal from'sweetalert2';
import'./style.css';
import'./auth.css';
import'./readability.css';
import'./admin.css';
import AdminCenter from'./AdminCenter.jsx';
import PortfolioSuite,{PublicPortfolio}from'./PortfolioSuite.jsx';
import'./suite.css';
import'./settings.css';
import'./dashboard-live.css';

const MCU_LOGO='https://lh3.googleusercontent.com/d/1d-tY28Km9oqKthhgl1s78aTrFa-gsYrP';
const API_URL=import.meta.env.VITE_API_URL||'/api/portfolio';
const GOOGLE_CLIENT_ID=import.meta.env.VITE_GOOGLE_CLIENT_ID||'';
const categoryIcons={'การจัดการเรียนการสอน':BookOpen,'วิจัยและวิชาการ':FlaskConical,'บริการวิชาการ':Handshake,'ทำนุบำรุงพระพุทธศาสนา':Landmark,'บริหารและงานประจำ':ClipboardCheck,'พัฒนาตนเอง':Sparkles};
const nav=[[LayoutDashboard,'ภาพรวม'],[FolderOpen,'แฟ้มผลงาน'],[ClipboardCheck,'รอบประเมิน'],[FileText,'รายงาน SAR'],[CheckCircle2,'กรรมการประเมิน'],[Users,'บุคลากร'],[UserRound,'โปรไฟล์ของฉัน'],[BarChart3,'รายงาน']];
async function api(params){const response=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(params)});const data=await response.json().catch(()=>({ok:false,message:'API ตอบกลับไม่ถูกต้อง'}));if(!response.ok||!data.ok)throw new Error(data.message||'ไม่สามารถดำเนินการได้');return data}
function loadGoogle(){return new Promise((resolve,reject)=>{if(window.google?.accounts)return resolve(window.google);const old=document.querySelector('script[data-gsi]');if(old){old.addEventListener('load',()=>resolve(window.google));return}const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.dataset.gsi='1';s.onload=()=>resolve(window.google);s.onerror=reject;document.head.appendChild(s)})}
function initials(name=''){return name.replace(/^(พระ|ดร\.|อาจารย์|นางสาว|นาย)/,'').trim().charAt(0)||'ผ'}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

function App(){
 const[active,setActive]=useState('ภาพรวม'),[q,setQ]=useState(''),[mobile,setMobile]=useState(false),[session,setSession]=useState(()=>JSON.parse(localStorage.getItem('mcu_session')||'null')),[profile,setProfile]=useState(null),[people,setPeople]=useState([]),[busy,setBusy]=useState(false),[adminData,setAdminData]=useState(null),[portfolioData,setPortfolioData]=useState(null),[notificationData,setNotificationData]=useState(null),[dashboardLoading,setDashboardLoading]=useState(false);
 const liveWorks=useMemo(()=>{const rows=(portfolioData?.works||[]).filter(w=>String(w['สถานะ']||w.status||'').toUpperCase()!=='TRASH');return rows.filter(w=>(String(w['ชื่อผลงาน']||'')+String(w['หมวดผลงาน']||'')).includes(q)).sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||'')))},[portfolioData,q]);
 useEffect(()=>{if(session?.token){refreshProfile(session.token);loadPeople(session.token);loadWorkspace(session.token)}applyPreferences()},[]);
 useEffect(()=>{if(active==='ภาพรวม'&&session?.token)loadWorkspace(session.token)},[active]);
 const isAdmin=['ADMIN','SUPER_ADMIN'].includes(String(session?.user?.role||'').toUpperCase());
 const loadAdmin=async token=>{try{const r=await api({action:'adminOverview',token:token||session?.token});setAdminData(r)}catch(e){Swal.fire({icon:'error',title:'เปิดศูนย์ผู้ดูแลไม่ได้',text:e.message,confirmButtonColor:'#d82f75'})}};
 const loadPeople=async token=>{try{const r=await api({action:'listPersonnel',token:token||session?.token});setPeople(r.people||[])}catch{setPeople([])}};
 const loadWorkspace=async token=>{if(!token)return;setDashboardLoading(true);try{const[p,n]=await Promise.all([api({action:'portfolioHome',token}),api({action:'notifications',token})]);setPortfolioData(p);setNotificationData(n)}catch(e){console.error('Dashboard load:',e.message)}finally{setDashboardLoading(false)}};
 const showNotifications=async()=>{if(!session?.token)return login();let data=notificationData;try{data=await api({action:'notifications',token:session.token});setNotificationData(data)}catch(e){return Swal.fire({icon:'error',title:'เปิดการแจ้งเตือนไม่สำเร็จ',text:e.message})}const items=data?.items||[],profileItem=profile?.missing?`<div class="notice-item warning"><b>โปรไฟล์ยังไม่ครบ</b><small>${escapeHtml(profile.missing)}</small></div>`:'';await Swal.fire({title:'ศูนย์แจ้งเตือน',width:760,html:`<div class="notice-summary"><span><b>${data?.summary?.revision||0}</b> ต้องแก้ไข</span><span><b>${data?.summary?.assigned||0}</b> งานประเมิน</span><span><b>${data?.summary?.pending||0}</b> รอตรวจ</span></div><div class="notice-list">${profileItem}${items.length?items.map(x=>`<div class="notice-item ${String(x.type).toLowerCase()}"><b>${escapeHtml(x.title||'กิจกรรม')}</b><small>${escapeHtml(x.detail||x.at||'')}</small></div>`).join(''):'<div class="notice-empty">ไม่มีรายการที่ต้องดำเนินการในขณะนี้</div>'}</div>`,confirmButtonText:'รับทราบ',confirmButtonColor:'#d82f75'})};
 const refreshProfile=async token=>{try{const r=await api({action:'getProfile',token});setProfile(r.profile);setSession(s=>({...s,user:r.user}))}catch(e){logout(false)}};
 const login=async()=>{if(!GOOGLE_CLIENT_ID)return Swal.fire({icon:'info',title:'รอตั้งค่าการเชื่อมต่อ',html:'ผู้ดูแลต้องกำหนด <b>VITE_GOOGLE_CLIENT_ID</b> ใน Vercel ก่อนเปิดใช้งานล็อกอิน',confirmButtonColor:'#d82f75'});setBusy(true);try{const google=await loadGoogle();google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:async({credential})=>{try{const r=await api({action:'login',credential});const next={token:r.token,user:r.user};localStorage.setItem('mcu_session',JSON.stringify(next));setSession(next);setProfile(r.profile);await loadWorkspace(next.token);setActive('ภาพรวม');await Swal.fire({icon:'success',title:'เข้าสู่ระบบสำเร็จ',text:`ยินดีต้อนรับ ${r.profile.name}`,confirmButtonColor:'#d82f75'})}catch(e){Swal.fire({icon:'error',title:'เข้าสู่ระบบไม่สำเร็จ',text:e.message,confirmButtonColor:'#d82f75'})}finally{setBusy(false)}}});google.accounts.id.prompt(n=>{if(n.isNotDisplayed()||n.isSkippedMoment()){google.accounts.id.renderButton(document.getElementById('google-login-fallback'),{theme:'outline',size:'large',text:'signin_with'})}})}catch(e){setBusy(false);Swal.fire({icon:'error',title:'เปิดระบบ Google ไม่สำเร็จ',text:e.message})}};
 const logout=async ask=>{if(ask){const r=await Swal.fire({icon:'question',title:'ออกจากระบบ?',showCancelButton:true,confirmButtonText:'ออกจากระบบ',cancelButtonText:'ยกเลิก',confirmButtonColor:'#d82f75'});if(!r.isConfirmed)return}localStorage.removeItem('mcu_session');setSession(null);setProfile(null);setPortfolioData(null);setNotificationData(null);setActive('ภาพรวม')};
 const openProfile=()=>{if(!session)return login();setActive('โปรไฟล์ของฉัน')};
 const saveProfile=async form=>{setBusy(true);try{const r=await api({action:'updateProfile',token:session.token,payload:form});setProfile(r.profile);await loadPeople(session.token);Swal.fire({icon:'success',title:'บันทึกข้อมูลแล้ว',text:'ระบบบันทึกประวัติการแก้ไขเรียบร้อย',confirmButtonColor:'#d82f75'})}catch(e){Swal.fire({icon:'error',title:'บันทึกไม่สำเร็จ',text:e.message,confirmButtonColor:'#d82f75'})}finally{setBusy(false)}};
 const saveAdminUser=async payload=>{setBusy(true);try{const r=await api({action:'adminUpdateUser',token:session.token,payload});setAdminData(r);await Swal.fire({icon:'success',title:'บันทึกสิทธิ์แล้ว',text:'ระบบบันทึก AuditLog เรียบร้อย',confirmButtonColor:'#d82f75'});return true}catch(e){Swal.fire({icon:'error',title:'บันทึกไม่สำเร็จ',text:e.message,confirmButtonColor:'#d82f75'});throw e}finally{setBusy(false)}};
 const createAdminPerson=async payload=>{setBusy(true);try{const r=await api({action:'adminCreatePerson',token:session.token,payload});setAdminData(r);await loadPeople(session.token);await Swal.fire({icon:'success',title:'เพิ่มบุคลากรแล้ว',text:'ระบบสร้างรหัสและบันทึก AuditLog เรียบร้อย',confirmButtonColor:'#d82f75'});return true}catch(e){Swal.fire({icon:'error',title:'เพิ่มบุคลากรไม่สำเร็จ',text:e.message,confirmButtonColor:'#d82f75'});throw e}finally{setBusy(false)}};
 const setAdminPersonActive=async payload=>{setBusy(true);try{const r=await api({action:'adminSetPersonActive',token:session.token,payload});setAdminData(r);await loadPeople(session.token);await Swal.fire({icon:'success',title:payload.active?'เปิดใช้งานแล้ว':'ระงับบัญชีแล้ว',text:'ข้อมูลเดิมยังอยู่ครบและบันทึก AuditLog แล้ว',confirmButtonColor:'#d82f75'});return true}catch(e){Swal.fire({icon:'error',title:'ดำเนินการไม่สำเร็จ',text:e.message,confirmButtonColor:'#d82f75'});throw e}finally{setBusy(false)}};
 const showAdminAudit=async()=>{setBusy(true);try{const r=await api({action:'adminAudit',token:session.token}),rows=(r.rows||[]).slice(0,30);await Swal.fire({title:'ประวัติการใช้งานล่าสุด',width:900,html:`<div style="text-align:left;max-height:520px;overflow:auto">${rows.map(x=>`<div style="padding:10px;border-bottom:1px solid #eee"><b>${x.action||x['การดำเนินการ']||'กิจกรรม'}</b><br><small>${x.timestamp||x['วันเวลา']||''} · ${x.actorEmail||x.email||''}</small></div>`).join('')}</div>`,confirmButtonColor:'#d82f75'})}catch(e){Swal.fire({icon:'error',title:'เปิด AuditLog ไม่สำเร็จ',text:e.message})}finally{setBusy(false)}};
 const backupAdminData=async()=>{const c=await Swal.fire({icon:'question',title:'สำรองข้อมูลตอนนี้?',text:'ระบบจะสร้างไฟล์สำรองทุกตารางไว้ใน Google Drive',showCancelButton:true,confirmButtonText:'สำรองข้อมูล',cancelButtonText:'ยกเลิก',confirmButtonColor:'#d82f75'});if(!c.isConfirmed)return;setBusy(true);try{const r=await api({action:'adminBackup',token:session.token});await Swal.fire({icon:'success',title:'สำรองข้อมูลแล้ว',html:r.file?.webViewLink?`<a href="${r.file.webViewLink}" target="_blank">เปิดไฟล์สำรองใน Google Drive</a>`:'บันทึกไฟล์สำรองเรียบร้อย',confirmButtonColor:'#d82f75'})}catch(e){Swal.fire({icon:'error',title:'สำรองข้อมูลไม่สำเร็จ',text:e.message})}finally{setBusy(false)}};
 const displayName=profile?.name||session?.user?.name||'ผู้ใช้งาน';
 return <div className="app">
 <aside className={mobile?'side open':'side'}><div className="brand"><img src={MCU_LOGO}/><div><b>Smart Portfolio</b><small>MCU KALASIN</small></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div><div className="ready">● ระบบพร้อมใช้งาน</div><p className="label">พื้นที่ทำงาน</p><nav>{nav.map(([I,n])=><button key={n} className={active===n?'on':''} onClick={()=>{n==='โปรไฟล์ของฉัน'?openProfile():setActive(n);setMobile(false)}}><I/>{n}{n==='กรรมการประเมิน'&&<em>3</em>}</button>)}</nav>{isAdmin&&<><p className="label">ผู้ดูแลระบบ</p><nav><button className={active==='ศูนย์ผู้ดูแลระบบ'?'on':''} onClick={()=>{setActive('ศูนย์ผู้ดูแลระบบ');loadAdmin();setMobile(false)}}><ShieldCheck/>ศูนย์ผู้ดูแลระบบ</button></nav></>}<p className="label">ระบบ</p><nav><button className={active==='ตั้งค่าระบบ'?'on':''} onClick={()=>{setActive('ตั้งค่าระบบ');setMobile(false)}}><Settings/>ตั้งค่าระบบ</button></nav><div className="progress-card"><div>84%</div><p><b>แฟ้มของคุณ</b><small>เหลืออีก 4 รายการ</small></p></div><button className="profile profile-button" onClick={openProfile}><span>{initials(displayName)}</span><p><b>{session?displayName:'เข้าสู่ระบบ'}</b><small>{profile?.position||'บุคลากร มจร กาฬสินธุ์'}</small></p></button></aside>
 <main><header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหาผลงาน เอกสาร หรือบุคลากร..."/></div><button className="bell live-bell" onClick={showNotifications}><Bell/>{notificationData?.summary?.total>0&&<i>{notificationData.summary.total}</i>}</button>{session?<button className="account" onClick={()=>logout(true)} title="ออกจากระบบ"><span className="avatar">{initials(displayName)}</span><LogOut/></button>:<button className="login" disabled={busy} onClick={login}><LogIn/>เข้าสู่ระบบ</button>}</header><div className="content">
 <section className="welcome"><div><small>แฟ้มสะสมผลงานดิจิทัล</small><h1>{active==='ภาพรวม'?`สวัสดีครับ${session?`, ${displayName}`:''} 👋`:active}</h1><p>{active==='ภาพรวม'?'ภาพรวมผลงานและความก้าวหน้าในรอบ ปีงบประมาณ 2569':'จัดการข้อมูลและติดตามผลอย่างเป็นระบบ'}</p></div><div>{session&&<button onClick={openProfile}><UserRound/>ข้อมูลของฉัน</button>}<button onClick={()=>{const slug=profile?.portfolioSlug||profile?.personId?.toLowerCase();if(!slug)return Swal.fire({icon:'info',title:'กรุณาเข้าสู่ระบบก่อน'});navigator.clipboard.writeText(`${location.origin}/?portfolio=${slug}`);Swal.fire({icon:'success',title:'คัดลอกลิงก์ Portfolio แล้ว',confirmButtonColor:'#d82f75'})}}><Share2/>แชร์ Portfolio</button><button className="primary" onClick={()=>session?setActive('แฟ้มผลงาน'):login()}><Plus/>เพิ่มผลงานใหม่</button></div></section>
 {active==='ภาพรวม'?<Dashboard data={portfolioData} profile={profile} loading={dashboardLoading} onRefresh={()=>loadWorkspace(session?.token)} onLogin={login}/>:active==='บุคลากร'?<Personnel people={people} q={q}/>:active==='โปรไฟล์ของฉัน'?<ProfileEditor profile={profile} session={session} busy={busy} onLogin={login} onSave={saveProfile}/>:active==='ศูนย์ผู้ดูแลระบบ'?<AdminCenter data={adminData} busy={busy} onSave={saveAdminUser} onCreate={createAdminPerson} onSetActive={setAdminPersonActive} onAudit={showAdminAudit} onBackup={backupAdminData}/>:active==='ตั้งค่าระบบ'?<SettingsCenter api={api} session={session} isAdmin={isAdmin} onOpenAdmin={()=>{setActive('ศูนย์ผู้ดูแลระบบ');loadAdmin()}}/>:<PortfolioSuite active={active} session={session} api={api} profile={profile} isAdmin={isAdmin}/>} {active==='ภาพรวม'&&session&&<RecentWorks rows={liveWorks}/>}</div></main>
 <div id="google-login-fallback" className="google-fallback"/></div>
}
const DEFAULT_PREFERENCES={fontScale:'1',density:'comfortable',notifications:true,defaultVisibility:'PUBLIC',confirmDelete:true};
function readPreferences(){try{return{...DEFAULT_PREFERENCES,...JSON.parse(localStorage.getItem('mcu_preferences')||'{}')}}catch{return DEFAULT_PREFERENCES}}
function applyPreferences(next=readPreferences()){document.documentElement.style.setProperty('--ui-scale',next.fontScale||'1');document.body.classList.toggle('ui-compact',next.density==='compact');return next}
function SettingsCenter({api,session,isAdmin,onOpenAdmin}){
 const[prefs,setPrefs]=useState(readPreferences),[health,setHealth]=useState(null),[checking,setChecking]=useState(false),[saved,setSaved]=useState(false);
 const update=(key,value)=>setPrefs(p=>({...p,[key]:value}));
 const save=()=>{localStorage.setItem('mcu_preferences',JSON.stringify(prefs));applyPreferences(prefs);setSaved(true);setTimeout(()=>setSaved(false),2200);Swal.fire({icon:'success',title:'บันทึกการตั้งค่าแล้ว',text:'ค่าการแสดงผลมีผลทันทีบนอุปกรณ์นี้',timer:1600,showConfirmButton:false})};
 const reset=()=>{setPrefs(DEFAULT_PREFERENCES);localStorage.removeItem('mcu_preferences');applyPreferences(DEFAULT_PREFERENCES);Swal.fire({icon:'success',title:'คืนค่าเริ่มต้นแล้ว',timer:1300,showConfirmButton:false})};
 const diagnose=async()=>{setChecking(true);try{const r=await api({action:'health'});setHealth({...r,checkedAt:new Date().toLocaleString('th-TH')})}catch(e){setHealth({ok:false,message:e.message,checkedAt:new Date().toLocaleString('th-TH')})}finally{setChecking(false)}};
 useEffect(()=>{diagnose()},[]);
 return <section className="settings-center">
  <div className="settings-hero"><div><small>SYSTEM PREFERENCES</small><h2>ศูนย์ตั้งค่าระบบ</h2><p>ปรับประสบการณ์ใช้งาน ตรวจการเชื่อมต่อ และกำหนดค่าเริ่มต้นของคุณ</p></div><Settings/></div>
  <div className="settings-grid">
   <article className="panel settings-card"><div className="settings-title"><Eye/><div><h3>การแสดงผล</h3><p>ปรับให้อ่านง่ายตามอุปกรณ์และสายตา</p></div></div>
    <label>ขนาดหน้าจอและตัวอักษร<select value={prefs.fontScale} onChange={e=>update('fontScale',e.target.value)}><option value="0.95">กะทัดรัด 95%</option><option value="1">มาตรฐาน 100%</option><option value="1.1">อ่านง่าย 110%</option><option value="1.2">ตัวใหญ่พิเศษ 120%</option></select></label>
    <label>ความหนาแน่นของข้อมูล<select value={prefs.density} onChange={e=>update('density',e.target.value)}><option value="comfortable">สบายตา</option><option value="compact">แสดงข้อมูลมากขึ้น</option></select></label>
    <div className="setting-preview"><b>ตัวอย่างการแสดงผล</b><span style={{fontSize:`calc(16px * ${prefs.fontScale})`}}>แฟ้มสะสมผลงานดิจิทัล อ่านง่ายและเป็นระบบ</span></div>
   </article>
   <article className="panel settings-card"><div className="settings-title"><MonitorCog/><div><h3>พฤติกรรมระบบ</h3><p>ตั้งค่าเริ่มต้นสำหรับการทำงานประจำวัน</p></div></div>
    <label className="setting-toggle"><span><b>เปิดการแจ้งเตือน</b><small>แจ้งงานที่ถูกขอแก้ไขและกำหนดสำคัญ</small></span><input type="checkbox" checked={prefs.notifications} onChange={e=>update('notifications',e.target.checked)}/></label>
    <label className="setting-toggle"><span><b>ยืนยันก่อนลบ</b><small>ลดความเสี่ยงจากการกดผิด</small></span><input type="checkbox" checked={prefs.confirmDelete} onChange={e=>update('confirmDelete',e.target.checked)}/></label>
    <label>สถานะ Portfolio เริ่มต้น<select value={prefs.defaultVisibility} onChange={e=>update('defaultVisibility',e.target.value)}><option value="PUBLIC">เผยแพร่สาธารณะ</option><option value="PRIVATE">เฉพาะเจ้าของและผู้ดูแล</option></select></label>
   </article>
   <article className="panel settings-card settings-wide"><div className="settings-title"><Database/><div><h3>สุขภาพระบบและการเชื่อมต่อ</h3><p>ตรวจสอบ API, Google Sheets และระบบยืนยันตัวตนแบบทันที</p></div><button className="settings-refresh" onClick={diagnose} disabled={checking}><RefreshCw className={checking?'spin':''}/>{checking?'กำลังตรวจ':'ตรวจอีกครั้ง'}</button></div>
    <div className="health-grid"><div className={health?.ok?'healthy':'unhealthy'}><i/ ><span><b>Portfolio API</b><small>{health?.ok?'พร้อมใช้งาน':health?.message||'กำลังตรวจสอบ'}</small></span></div><div className={health?.database?'healthy':'pending-health'}><i/><span><b>Google Sheets</b><small>{health?.database||'รอผลตรวจ'}</small></span></div><div className={health?.auth?'healthy':'pending-health'}><i/><span><b>Google Identity / WIF</b><small>{health?.auth||'รอผลตรวจ'}</small></span></div><div className={session?'healthy':'pending-health'}><i/><span><b>บัญชีผู้ใช้งาน</b><small>{session?`เชื่อมต่อแล้ว · ${session.user?.email||''}`:'ยังไม่ได้เข้าสู่ระบบ'}</small></span></div></div>
    <p className="health-note">เวอร์ชัน {health?.version||'–'} · ผู้ใช้ในระบบ {health?.users??'–'} บัญชี · ตรวจล่าสุด {health?.checkedAt||'–'}</p>
   </article>
   {isAdmin&&<article className="panel settings-card settings-wide admin-settings"><div className="settings-title"><ShieldCheck/><div><h3>เครื่องมือสำหรับผู้ดูแลระบบ</h3><p>ทางลัดไปยังส่วนควบคุมข้อมูลสำคัญของหน่วยงาน</p></div></div><div className="admin-setting-links"><button onClick={onOpenAdmin}><Users/>จัดการบัญชีบุคลากร</button><button onClick={()=>Swal.fire({icon:'info',title:'การตั้งค่าระดับองค์กร',text:'ข้อมูลส่วนกลางจัดการจากศูนย์ผู้ดูแลระบบและ Google Sheet เพื่อให้มี AuditLog ครบถ้วน',confirmButtonColor:'#d82f75'})}><HardDrive/>ข้อมูลกลางและ Drive</button><button onClick={diagnose}><RefreshCw/>ตรวจการเชื่อมต่อ</button></div></article>}
  </div>
  <div className="settings-actions"><button onClick={reset}>คืนค่าเริ่มต้น</button><button className="primary" onClick={save}><Save/>{saved?'บันทึกแล้ว':'บันทึกการตั้งค่า'}</button></div>
 </section>
}
function Dashboard({data,profile,loading,onRefresh,onLogin}){
 if(!data)return <div className="panel live-empty"><Database/><h2>{loading?'กำลังอ่านข้อมูลจาก Google Sheets…':'ภาพรวมพร้อมเชื่อมข้อมูลจริง'}</h2><p>เข้าสู่ระบบเพื่อดูผลงาน หลักฐาน รอบประเมิน และความครบถ้วนของบัญชีคุณ</p>{!loading&&<button className="primary" onClick={onLogin}><LogIn/>เข้าสู่ระบบด้วย Google</button>}</div>;
 const works=(data.works||[]).filter(w=>String(w['สถานะ']||w.status||'').toUpperCase()!=='TRASH'),evidence=data.evidence||[],state=w=>String(w['สถานะ']||w.status||'').toUpperCase(),pending=works.filter(w=>['SUBMITTED','PENDING','รอตรวจ'].includes(state(w))).length,approved=works.filter(w=>['APPROVED','รับรองแล้ว'].includes(state(w))).length,complete=works.filter(w=>String(w['รายละเอียด/ผลลัพธ์']||'').trim()&&evidence.some(e=>e.workId===w.workId)).length,completeness=works.length?Math.round(complete/works.length*100):0;
 const categories=Object.keys(categoryIcons).map(name=>{const rows=works.filter(w=>String(w['หมวดผลงาน']||'')===name),withEvidence=rows.filter(w=>evidence.some(e=>e.workId===w.workId)).length;return{name,count:rows.length,percent:rows.length?Math.round(withEvidence/rows.length*100):0,Icon:categoryIcons[name]}});
 const round=(data.rounds||[]).find(r=>['ACTIVE','OPEN','เปิดใช้งาน','กำลังดำเนินการ'].includes(String(r['สถานะ']||r.status)))||(data.rounds||[])[0],due=round?.['วันปิดส่งหลักฐาน']||round?.endDate||'',date=due?new Date(due):null,days=date&&!Number.isNaN(date.getTime())?Math.ceil((date-new Date())/86400000):null;
 return <>{loading&&<div className="live-sync"><RefreshCw/>กำลังซิงก์ข้อมูลล่าสุด…</div>}<section className="stats"><Card icon={<FolderOpen/>} title="ผลงานทั้งหมด" value={works.length} sub={`${evidence.length} หลักฐานในระบบ`}/><Card icon={<Clock3/>} title="รอการประเมิน" value={pending} sub={pending?'อยู่ในคิวกรรมการ':'ไม่มีงานค้างตรวจ'}/><Card icon={<CheckCircle2/>} title="รับรองแล้ว" value={approved} sub={`${works.length?Math.round(approved/works.length*100):0}% ของผลงานทั้งหมด`}/><Card icon={<BarChart3/>} title="ความครบถ้วน" value={`${completeness}%`} sub={`ครบทั้งรายละเอียดและหลักฐาน ${complete}/${works.length}`}/></section><section className="columns"><div className="panel"><div className="live-panel-head"><Head title="ความครบถ้วนตามพันธกิจ" sub="คำนวณจากผลงานและหลักฐานจริง"/><button onClick={onRefresh}><RefreshCw/>รีเฟรช</button></div><div className="cats">{categories.map(({Icon,name,count,percent})=><article key={name}><div><Icon/><small>{count} ผลงาน</small></div><b>{name}</b><i><span style={{width:percent+'%'}}/></i><small>{count?`${percent}% มีหลักฐานครบ`:'ยังไม่มีผลงาน'}</small></article>)}</div></div><div className="panel deadline"><Head title="กำหนดการสำคัญ" sub="รอบประเมินจากข้อมูลกลาง"/>{round?<><div className="date"><b>{date&&!Number.isNaN(date.getTime())?date.getDate():'–'}</b><span>{date&&!Number.isNaN(date.getTime())?date.toLocaleDateString('th-TH',{month:'short'}):'รอกำหนด'}</span><p><b>{round['ชื่อรอบประเมิน']||round.name||'รอบประเมินปัจจุบัน'}</b><small>{days===null?'ยังไม่กำหนดวันปิดส่ง':days<0?'ปิดรับหลักฐานแล้ว':`เหลือเวลา ${days} วัน`}</small></p></div><div className="step done"><i>✓</i><p><b>เปิดรอบประเมิน</b><small>{round['ประเภท']||'ปีงบประมาณ 2569'}</small></p></div><div className={works.length?'step done':'step current'}><i>{works.length?'✓':'2'}</i><p><b>บันทึกผลงาน</b><small>{works.length?`${works.length} รายการ`:'รอเพิ่มผลงาน'}</small></p></div><div className={pending?'step current':'step'}><i>3</i><p><b>ส่งหลักฐานให้กรรมการ</b><small>{pending?`${pending} รายการกำลังตรวจ`:'ยังไม่มีรายการรอตรวจ'}</small></p></div><div className={approved?'step done':'step'}><i>{approved?'✓':'4'}</i><p><b>รับรองผล</b><small>{approved} รายการรับรองแล้ว</small></p></div></>:<div className="round-empty"><ClipboardCheck/><b>ยังไม่มีรอบประเมิน</b><small>ผู้ดูแลเพิ่มได้ในชีต EvaluationRounds</small></div>}</div></section></>
}
function RecentWorks({rows}){return <section className="panel table live-recent"><Head title="ผลงานล่าสุด" sub="รายการจริงจาก Google Sheets"/>{rows.slice(0,6).map(w=>{const status=String(w['สถานะ']||w.status||'DRAFT'),label={DRAFT:'ฉบับร่าง',SUBMITTED:'รอตรวจ',PENDING:'รอตรวจ',REVISION:'ขอแก้ไข',APPROVED:'รับรองแล้ว'}[status.toUpperCase()]||status;return <div className="row" key={w.workId}><span className="file"><FileText/></span><p><b>{w['ชื่อผลงาน']||'ไม่ระบุชื่อ'}</b><small>{w['หมวดผลงาน']||'ไม่ระบุหมวด'} · {formatThaiDate(w.updatedAt||w.createdAt)}</small></p><em className={label}>{label}</em><b className="work-code">{w.workId}</b></div>})}{!rows.length&&<div className="recent-empty">ยังไม่มีผลงาน กด “เพิ่มผลงานใหม่” เพื่อเริ่มแฟ้มของคุณ</div>}</section>}
function formatThaiDate(value){const d=new Date(value);return value&&!Number.isNaN(d.getTime())?d.toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'}):'ยังไม่ระบุวันที่'}
function Personnel({people,q}){const rows=people.filter(p=>(p.name+p.position+p.department).includes(q));return <section className="module"><div className="stats"><Card icon={<Users/>} title="บุคลากรทั้งหมด" value={people.length||25} sub="บัญชีในระบบ"/><Card icon={<ShieldCheck/>} title="ควบคุมสิทธิ์" value="เฉพาะตน" sub="ผู้ดูแลแก้ไขได้ทุกคน"/><Card icon={<Clock3/>} title="รอผูกอีเมล" value={people.filter(p=>!p.email).length||24} sub="เพิ่มอีเมลเพื่อเปิดบัญชี"/></div><div className="panel people"><Head title="ทำเนียบบุคลากร" sub="ข้อมูลกลางสำหรับแฟ้มสะสมผลงาน"/>{rows.map(p=><article key={p.personId}>{p.photoUrl?<img src={p.photoUrl}/>:<span>{initials(p.name)}</span>}<p><b>{p.name}</b><small>{p.position}</small></p><em className={p.dataStatus==='ข้อมูลครบถ้วน'?'complete':'pending'}>{p.dataStatus}</em><button>ดู Portfolio</button></article>)}</div></section>}
function ProfileEditor({profile,session,busy,onLogin,onSave}){const[form,setForm]=useState({});useEffect(()=>setForm(profile?{prefix:profile.prefix||'',name:profile.name||'',phone:profile.phone||'',photoUrl:profile.photoUrl||''}:{}),[profile]);if(!session)return <div className="panel auth-card"><KeyRound/><h2>เข้าสู่ระบบเพื่อแก้ไขข้อมูลของคุณ</h2><p>ระบบจะตรวจอีเมล Google กับบัญชีบุคลากร และเปิดเฉพาะข้อมูลของเจ้าของบัญชี</p><button className="primary" onClick={onLogin}><LogIn/>เข้าสู่ระบบด้วย Google</button></div>;if(!profile)return <div className="panel auth-card"><Clock3/><h2>กำลังโหลดข้อมูล…</h2></div>;const set=(k,v)=>setForm(f=>({...f,[k]:v}));return <section className="profile-layout"><div className="panel identity-card">{form.photoUrl?<img src={form.photoUrl}/>:<span>{initials(form.name)}</span>}<h2>{profile.name}</h2><p>{profile.position}</p><div><ShieldCheck/>บัญชีได้รับการยืนยันด้วย Google</div><small>{profile.email}</small><small>รหัสบุคลากร: {profile.personId}</small></div><form className="panel profile-form" onSubmit={e=>{e.preventDefault();onSave(form)}}><Head title="แก้ไขข้อมูลของฉัน" sub="แก้ไขได้เฉพาะข้อมูลส่วนตัว ส่วนตำแหน่งและสิทธิ์ให้ผู้ดูแลระบบเป็นผู้แก้ไข"/><div className="formgrid"><label>คำนำหน้า/สมณศักดิ์<input value={form.prefix} onChange={e=>set('prefix',e.target.value)}/></label><label>ชื่อ-ฉายา/นามสกุล<input required value={form.name} onChange={e=>set('name',e.target.value)}/></label></div><div className="formgrid"><label>อีเมลบัญชี Google<input disabled value={profile.email||''}/><small>ใช้ยืนยันตัวตน จึงแก้ไขจากหน้านี้ไม่ได้</small></label><label>หมายเลขโทรศัพท์<input type="tel" inputMode="numeric" pattern="0[0-9]{8,9}" title="กรุณากรอกหมายเลขที่ขึ้นต้นด้วย 0 จำนวน 9–10 หลัก" value={form.phone} onChange={e=>set('phone',e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="เช่น 0812345678"/></label></div><label>URL รูปบุคลากร<input type="url" value={form.photoUrl} onChange={e=>set('photoUrl',e.target.value)} placeholder="ลิงก์รูปภาพจาก Google Drive"/></label><label>ตำแหน่ง<input disabled value={profile.position||''}/></label><div className="missing"><b>ข้อมูลที่ยังขาด</b><span>{profile.missing||'ไม่มี — ข้อมูลครบถ้วนแล้ว'}</span></div><button disabled={busy} className="primary save"><Save/>{busy?'กำลังบันทึก…':'บันทึกข้อมูลของฉัน'}</button></form></section>}
function Card({icon,title,value,sub}){return <article className="card"><span>{icon}</span><p><small>{title}</small><b>{value}</b><em>{sub}</em></p></article>}function Head({title,sub}){return <div className="head"><div><h2>{title}</h2><p>{sub}</p></div></div>}function Module({active}){return <section className="module"><div className="stats"><Card icon={<CheckCircle2/>} title="ข้อมูลครบถ้วน" value="42" sub="รายการ"/><Card icon={<Clock3/>} title="กำลังดำเนินการ" value="6" sub="รายการ"/><Card icon={<ClipboardCheck/>} title="รอตรวจรับรอง" value="3" sub="รายการ"/></div><div className="panel auth-card"><Settings/><h2>{active}</h2><p>โมดูลพร้อมเชื่อมต่อฐานข้อมูลในลำดับถัดไป</p></div></section>}
const publicSlug=new URLSearchParams(location.search).get('portfolio');
createRoot(document.getElementById('root')).render(publicSlug?<PublicPortfolio api={api} slug={publicSlug}/>:<App/>);
