import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{LayoutDashboard,FolderOpen,ClipboardCheck,FileText,Users,BarChart3,Settings,Search,Plus,Share2,Bell,CheckCircle2,Clock3,BookOpen,FlaskConical,Handshake,Landmark,Sparkles,Upload,Menu,X,LogIn,LogOut,UserRound,Save,ShieldCheck,KeyRound}from'lucide-react';
import Swal from'sweetalert2';
import'./style.css';
import'./auth.css';
import'./readability.css';
import'./admin.css';
import AdminCenter from'./AdminCenter.jsx';
import PortfolioSuite,{PublicPortfolio}from'./PortfolioSuite.jsx';
import'./suite.css';

const MCU_LOGO='https://lh3.googleusercontent.com/d/1d-tY28Km9oqKthhgl1s78aTrFa-gsYrP';
const API_URL=import.meta.env.VITE_API_URL||'/api/portfolio';
const GOOGLE_CLIENT_ID=import.meta.env.VITE_GOOGLE_CLIENT_ID||'';
const works=[['พัฒนาระบบตอบรับพิธีมอบประกาศนียบัตร ป.บส.','บริหารและงานประจำ','รับรองแล้ว',100],['โครงการอบรมพระนักเทศน์ Kalasin NextGen รุ่นที่ 2','บริการวิชาการ','รอตรวจ',82],['ระบบประเมินผลโครงการแบบออนไลน์','นวัตกรรมและเทคโนโลยี','รับรองแล้ว',100],['รายงานผลการปฏิบัติงาน ไตรมาส 3','รายงานและ SAR','ฉบับร่าง',46]];
const cats=[[BookOpen,'การจัดการเรียนการสอน',8,80],[FlaskConical,'วิจัยและวิชาการ',3,60],[Handshake,'บริการวิชาการ',12,92],[Landmark,'ทำนุบำรุงพระพุทธศาสนา',9,88],[ClipboardCheck,'บริหารและงานประจำ',16,100],[Sparkles,'พัฒนาตนเอง',6,75]];
const nav=[[LayoutDashboard,'ภาพรวม'],[FolderOpen,'แฟ้มผลงาน'],[ClipboardCheck,'รอบประเมิน'],[FileText,'รายงาน SAR'],[CheckCircle2,'กรรมการประเมิน'],[Users,'บุคลากร'],[UserRound,'โปรไฟล์ของฉัน'],[BarChart3,'รายงาน']];
async function api(params){const response=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(params)});const data=await response.json().catch(()=>({ok:false,message:'API ตอบกลับไม่ถูกต้อง'}));if(!response.ok||!data.ok)throw new Error(data.message||'ไม่สามารถดำเนินการได้');return data}
function loadGoogle(){return new Promise((resolve,reject)=>{if(window.google?.accounts)return resolve(window.google);const old=document.querySelector('script[data-gsi]');if(old){old.addEventListener('load',()=>resolve(window.google));return}const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.dataset.gsi='1';s.onload=()=>resolve(window.google);s.onerror=reject;document.head.appendChild(s)})}
function initials(name=''){return name.replace(/^(พระ|ดร\.|อาจารย์|นางสาว|นาย)/,'').trim().charAt(0)||'ผ'}

function App(){
 const[active,setActive]=useState('ภาพรวม'),[q,setQ]=useState(''),[modal,setModal]=useState(false),[mobile,setMobile]=useState(false),[session,setSession]=useState(()=>JSON.parse(localStorage.getItem('mcu_session')||'null')),[profile,setProfile]=useState(null),[people,setPeople]=useState([]),[busy,setBusy]=useState(false),[adminData,setAdminData]=useState(null);
 const filtered=useMemo(()=>works.filter(w=>(w[0]+w[1]).includes(q)),[q]);
 useEffect(()=>{if(session?.token){refreshProfile(session.token);loadPeople(session.token)}},[]);
 const isAdmin=['ADMIN','SUPER_ADMIN'].includes(String(session?.user?.role||'').toUpperCase());
 const loadAdmin=async token=>{try{const r=await api({action:'adminOverview',token:token||session?.token});setAdminData(r)}catch(e){Swal.fire({icon:'error',title:'เปิดศูนย์ผู้ดูแลไม่ได้',text:e.message,confirmButtonColor:'#d82f75'})}};
 const loadPeople=async token=>{try{const r=await api({action:'listPersonnel',token:token||session?.token});setPeople(r.people||[])}catch{setPeople([])}};
 const refreshProfile=async token=>{try{const r=await api({action:'getProfile',token});setProfile(r.profile);setSession(s=>({...s,user:r.user}))}catch(e){logout(false)}};
 const login=async()=>{if(!GOOGLE_CLIENT_ID)return Swal.fire({icon:'info',title:'รอตั้งค่าการเชื่อมต่อ',html:'ผู้ดูแลต้องกำหนด <b>VITE_GOOGLE_CLIENT_ID</b> ใน Vercel ก่อนเปิดใช้งานล็อกอิน',confirmButtonColor:'#d82f75'});setBusy(true);try{const google=await loadGoogle();google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:async({credential})=>{try{const r=await api({action:'login',credential});const next={token:r.token,user:r.user};localStorage.setItem('mcu_session',JSON.stringify(next));setSession(next);setProfile(r.profile);setActive('โปรไฟล์ของฉัน');await Swal.fire({icon:'success',title:'เข้าสู่ระบบสำเร็จ',text:`ยินดีต้อนรับ ${r.profile.name}`,confirmButtonColor:'#d82f75'})}catch(e){Swal.fire({icon:'error',title:'เข้าสู่ระบบไม่สำเร็จ',text:e.message,confirmButtonColor:'#d82f75'})}finally{setBusy(false)}}});google.accounts.id.prompt(n=>{if(n.isNotDisplayed()||n.isSkippedMoment()){google.accounts.id.renderButton(document.getElementById('google-login-fallback'),{theme:'outline',size:'large',text:'signin_with'})}})}catch(e){setBusy(false);Swal.fire({icon:'error',title:'เปิดระบบ Google ไม่สำเร็จ',text:e.message})}};
 const logout=async ask=>{if(ask){const r=await Swal.fire({icon:'question',title:'ออกจากระบบ?',showCancelButton:true,confirmButtonText:'ออกจากระบบ',cancelButtonText:'ยกเลิก',confirmButtonColor:'#d82f75'});if(!r.isConfirmed)return}localStorage.removeItem('mcu_session');setSession(null);setProfile(null);setActive('ภาพรวม')};
 const openProfile=()=>{if(!session)return login();setActive('โปรไฟล์ของฉัน')};
 const saveProfile=async form=>{setBusy(true);try{const r=await api({action:'updateProfile',token:session.token,payload:form});setProfile(r.profile);await loadPeople(session.token);Swal.fire({icon:'success',title:'บันทึกข้อมูลแล้ว',text:'ระบบบันทึกประวัติการแก้ไขเรียบร้อย',confirmButtonColor:'#d82f75'})}catch(e){Swal.fire({icon:'error',title:'บันทึกไม่สำเร็จ',text:e.message,confirmButtonColor:'#d82f75'})}finally{setBusy(false)}};
 const saveAdminUser=async payload=>{setBusy(true);try{const r=await api({action:'adminUpdateUser',token:session.token,payload});setAdminData(r);await Swal.fire({icon:'success',title:'บันทึกสิทธิ์แล้ว',text:'ระบบบันทึก AuditLog เรียบร้อย',confirmButtonColor:'#d82f75'});return true}catch(e){Swal.fire({icon:'error',title:'บันทึกไม่สำเร็จ',text:e.message,confirmButtonColor:'#d82f75'});throw e}finally{setBusy(false)}};
 const createAdminPerson=async payload=>{setBusy(true);try{const r=await api({action:'adminCreatePerson',token:session.token,payload});setAdminData(r);await loadPeople(session.token);await Swal.fire({icon:'success',title:'เพิ่มบุคลากรแล้ว',text:'ระบบสร้างรหัสและบันทึก AuditLog เรียบร้อย',confirmButtonColor:'#d82f75'});return true}catch(e){Swal.fire({icon:'error',title:'เพิ่มบุคลากรไม่สำเร็จ',text:e.message,confirmButtonColor:'#d82f75'});throw e}finally{setBusy(false)}};
 const setAdminPersonActive=async payload=>{setBusy(true);try{const r=await api({action:'adminSetPersonActive',token:session.token,payload});setAdminData(r);await loadPeople(session.token);await Swal.fire({icon:'success',title:payload.active?'เปิดใช้งานแล้ว':'ระงับบัญชีแล้ว',text:'ข้อมูลเดิมยังอยู่ครบและบันทึก AuditLog แล้ว',confirmButtonColor:'#d82f75'});return true}catch(e){Swal.fire({icon:'error',title:'ดำเนินการไม่สำเร็จ',text:e.message,confirmButtonColor:'#d82f75'});throw e}finally{setBusy(false)}};
 const showAdminAudit=async()=>{setBusy(true);try{const r=await api({action:'adminAudit',token:session.token}),rows=(r.rows||[]).slice(0,30);await Swal.fire({title:'ประวัติการใช้งานล่าสุด',width:900,html:`<div style="text-align:left;max-height:520px;overflow:auto">${rows.map(x=>`<div style="padding:10px;border-bottom:1px solid #eee"><b>${x.action||x['การดำเนินการ']||'กิจกรรม'}</b><br><small>${x.timestamp||x['วันเวลา']||''} · ${x.actorEmail||x.email||''}</small></div>`).join('')}</div>`,confirmButtonColor:'#d82f75'})}catch(e){Swal.fire({icon:'error',title:'เปิด AuditLog ไม่สำเร็จ',text:e.message})}finally{setBusy(false)}};
 const backupAdminData=async()=>{const c=await Swal.fire({icon:'question',title:'สำรองข้อมูลตอนนี้?',text:'ระบบจะสร้างไฟล์สำรองทุกตารางไว้ใน Google Drive',showCancelButton:true,confirmButtonText:'สำรองข้อมูล',cancelButtonText:'ยกเลิก',confirmButtonColor:'#d82f75'});if(!c.isConfirmed)return;setBusy(true);try{const r=await api({action:'adminBackup',token:session.token});await Swal.fire({icon:'success',title:'สำรองข้อมูลแล้ว',html:r.file?.webViewLink?`<a href="${r.file.webViewLink}" target="_blank">เปิดไฟล์สำรองใน Google Drive</a>`:'บันทึกไฟล์สำรองเรียบร้อย',confirmButtonColor:'#d82f75'})}catch(e){Swal.fire({icon:'error',title:'สำรองข้อมูลไม่สำเร็จ',text:e.message})}finally{setBusy(false)}};
 const displayName=profile?.name||session?.user?.name||'ผู้ใช้งาน';
 return <div className="app">
 <aside className={mobile?'side open':'side'}><div className="brand"><img src={MCU_LOGO}/><div><b>Smart Portfolio</b><small>MCU KALASIN</small></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div><div className="ready">● ระบบพร้อมใช้งาน</div><p className="label">พื้นที่ทำงาน</p><nav>{nav.map(([I,n])=><button key={n} className={active===n?'on':''} onClick={()=>{n==='โปรไฟล์ของฉัน'?openProfile():setActive(n);setMobile(false)}}><I/>{n}{n==='กรรมการประเมิน'&&<em>3</em>}</button>)}</nav>{isAdmin&&<><p className="label">ผู้ดูแลระบบ</p><nav><button className={active==='ศูนย์ผู้ดูแลระบบ'?'on':''} onClick={()=>{setActive('ศูนย์ผู้ดูแลระบบ');loadAdmin();setMobile(false)}}><ShieldCheck/>ศูนย์ผู้ดูแลระบบ</button></nav></>}<p className="label">ระบบ</p><nav><button><Settings/>ตั้งค่าระบบ</button></nav><div className="progress-card"><div>84%</div><p><b>แฟ้มของคุณ</b><small>เหลืออีก 4 รายการ</small></p></div><button className="profile profile-button" onClick={openProfile}><span>{initials(displayName)}</span><p><b>{session?displayName:'เข้าสู่ระบบ'}</b><small>{profile?.position||'บุคลากร มจร กาฬสินธุ์'}</small></p></button></aside>
 <main><header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหาผลงาน เอกสาร หรือบุคลากร..."/></div><button className="bell" onClick={()=>Swal.fire({icon:profile?.missing?'warning':'success',title:'การแจ้งเตือน',html:session?(profile?.missing?`<b>โปรไฟล์ยังไม่ครบ</b><br>${profile.missing}<br><br>กรุณาเติมข้อมูลเพื่อให้แฟ้มสมบูรณ์`:'ยังไม่มีรายการเร่งด่วน<br>ข้อมูลบัญชีของคุณครบถ้วนแล้ว'):'เข้าสู่ระบบเพื่อดูรายการที่ต้องดำเนินการ',confirmButtonColor:'#d82f75'})}><Bell/></button>{session?<button className="account" onClick={()=>logout(true)} title="ออกจากระบบ"><span className="avatar">{initials(displayName)}</span><LogOut/></button>:<button className="login" disabled={busy} onClick={login}><LogIn/>เข้าสู่ระบบ</button>}</header><div className="content">
 <section className="welcome"><div><small>แฟ้มสะสมผลงานดิจิทัล</small><h1>{active==='ภาพรวม'?`สวัสดีครับ${session?`, ${displayName}`:''} 👋`:active}</h1><p>{active==='ภาพรวม'?'ภาพรวมผลงานและความก้าวหน้าในรอบ ปีงบประมาณ 2569':'จัดการข้อมูลและติดตามผลอย่างเป็นระบบ'}</p></div><div>{session&&<button onClick={openProfile}><UserRound/>ข้อมูลของฉัน</button>}<button onClick={()=>{const slug=profile?.portfolioSlug||profile?.personId?.toLowerCase();if(!slug)return Swal.fire({icon:'info',title:'กรุณาเข้าสู่ระบบก่อน'});navigator.clipboard.writeText(`${location.origin}/?portfolio=${slug}`);Swal.fire({icon:'success',title:'คัดลอกลิงก์ Portfolio แล้ว',confirmButtonColor:'#d82f75'})}}><Share2/>แชร์ Portfolio</button><button className="primary" onClick={()=>session?setActive('แฟ้มผลงาน'):login()}><Plus/>เพิ่มผลงานใหม่</button></div></section>
 {active==='ภาพรวม'?<Dashboard/>:active==='บุคลากร'?<Personnel people={people} q={q}/>:active==='โปรไฟล์ของฉัน'?<ProfileEditor profile={profile} session={session} busy={busy} onLogin={login} onSave={saveProfile}/>:active==='ศูนย์ผู้ดูแลระบบ'?<AdminCenter data={adminData} busy={busy} onSave={saveAdminUser} onCreate={createAdminPerson} onSetActive={setAdminPersonActive} onAudit={showAdminAudit} onBackup={backupAdminData}/>:<PortfolioSuite active={active} session={session} api={api} profile={profile} isAdmin={isAdmin}/>}<section className="panel table"><Head title="ผลงานล่าสุด" sub="รายการที่เพิ่มและแก้ไขล่าสุด"/>{filtered.map((w,i)=><div className="row" key={w[0]}><span className="file"><FileText/></span><p><b>{w[0]}</b><small>{w[1]} · {i+12} ก.ค. 2569</small></p><em className={w[2]}>{w[2]}</em><div className="bar"><span style={{width:w[3]+'%'}}/></div><b>{w[3]}%</b></div>)}</section></div></main>
 {modal&&<WorkModal onClose={()=>setModal(false)}/>}<div id="google-login-fallback" className="google-fallback"/></div>
}
function Dashboard(){return <><section className="stats"><Card icon={<FolderOpen/>} title="ผลงานทั้งหมด" value="54" sub="12 รายการในรอบนี้"/><Card icon={<Clock3/>} title="รอการประเมิน" value="6" sub="ส่งตรวจล่าสุด 2 วันก่อน"/><Card icon={<CheckCircle2/>} title="รับรองแล้ว" value="42" sub="78% ของผลงานทั้งหมด"/><Card icon={<BarChart3/>} title="ความครบถ้วน" value="84%" sub="ครบแล้ว 16 จาก 20 ตัวชี้วัด"/></section><section className="columns"><div className="panel"><Head title="ความครบถ้วนตามพันธกิจ" sub="สรุปหลักฐานในแต่ละหมวดงาน"/><div className="cats">{cats.map(([I,n,c,p])=><article key={n}><div><I/><small>{c} ผลงาน</small></div><b>{n}</b><i><span style={{width:p+'%'}}/></i><small>{p}% ครบถ้วน</small></article>)}</div></div><div className="panel deadline"><Head title="กำหนดการสำคัญ" sub="รอบประเมินปัจจุบัน"/><div className="date"><b>30</b><span>ก.ย.</span><p><b>ส่งรายงานผลการปฏิบัติงาน</b><small>เหลือเวลา 71 วัน</small></p></div>{['เปิดรอบประเมิน','บันทึกข้อตกลงการปฏิบัติงาน','รวบรวมและส่งหลักฐาน','กรรมการตรวจประเมิน'].map((x,i)=><div key={x} className={i<2?'step done':i===2?'step current':'step'}><i>{i<2?'✓':i+1}</i><p><b>{x}</b><small>{i===2?'กำลังดำเนินการ':'ปีงบประมาณ 2569'}</small></p></div>)}</div></section></>}
function Personnel({people,q}){const rows=people.filter(p=>(p.name+p.position+p.department).includes(q));return <section className="module"><div className="stats"><Card icon={<Users/>} title="บุคลากรทั้งหมด" value={people.length||25} sub="บัญชีในระบบ"/><Card icon={<ShieldCheck/>} title="ควบคุมสิทธิ์" value="เฉพาะตน" sub="ผู้ดูแลแก้ไขได้ทุกคน"/><Card icon={<Clock3/>} title="รอผูกอีเมล" value={people.filter(p=>!p.email).length||24} sub="เพิ่มอีเมลเพื่อเปิดบัญชี"/></div><div className="panel people"><Head title="ทำเนียบบุคลากร" sub="ข้อมูลกลางสำหรับแฟ้มสะสมผลงาน"/>{rows.map(p=><article key={p.personId}>{p.photoUrl?<img src={p.photoUrl}/>:<span>{initials(p.name)}</span>}<p><b>{p.name}</b><small>{p.position}</small></p><em className={p.dataStatus==='ข้อมูลครบถ้วน'?'complete':'pending'}>{p.dataStatus}</em><button>ดู Portfolio</button></article>)}</div></section>}
function ProfileEditor({profile,session,busy,onLogin,onSave}){const[form,setForm]=useState({});useEffect(()=>setForm(profile?{prefix:profile.prefix||'',name:profile.name||'',phone:profile.phone||'',photoUrl:profile.photoUrl||''}:{}),[profile]);if(!session)return <div className="panel auth-card"><KeyRound/><h2>เข้าสู่ระบบเพื่อแก้ไขข้อมูลของคุณ</h2><p>ระบบจะตรวจอีเมล Google กับบัญชีบุคลากร และเปิดเฉพาะข้อมูลของเจ้าของบัญชี</p><button className="primary" onClick={onLogin}><LogIn/>เข้าสู่ระบบด้วย Google</button></div>;if(!profile)return <div className="panel auth-card"><Clock3/><h2>กำลังโหลดข้อมูล…</h2></div>;const set=(k,v)=>setForm(f=>({...f,[k]:v}));return <section className="profile-layout"><div className="panel identity-card">{form.photoUrl?<img src={form.photoUrl}/>:<span>{initials(form.name)}</span>}<h2>{profile.name}</h2><p>{profile.position}</p><div><ShieldCheck/>บัญชีได้รับการยืนยันด้วย Google</div><small>{profile.email}</small><small>รหัสบุคลากร: {profile.personId}</small></div><form className="panel profile-form" onSubmit={e=>{e.preventDefault();onSave(form)}}><Head title="แก้ไขข้อมูลของฉัน" sub="แก้ไขได้เฉพาะข้อมูลส่วนตัว ส่วนตำแหน่งและสิทธิ์ให้ผู้ดูแลระบบเป็นผู้แก้ไข"/><div className="formgrid"><label>คำนำหน้า/สมณศักดิ์<input value={form.prefix} onChange={e=>set('prefix',e.target.value)}/></label><label>ชื่อ-ฉายา/นามสกุล<input required value={form.name} onChange={e=>set('name',e.target.value)}/></label></div><div className="formgrid"><label>อีเมลบัญชี Google<input disabled value={profile.email||''}/><small>ใช้ยืนยันตัวตน จึงแก้ไขจากหน้านี้ไม่ได้</small></label><label>หมายเลขโทรศัพท์<input type="tel" inputMode="numeric" pattern="0[0-9]{8,9}" title="กรุณากรอกหมายเลขที่ขึ้นต้นด้วย 0 จำนวน 9–10 หลัก" value={form.phone} onChange={e=>set('phone',e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="เช่น 0812345678"/></label></div><label>URL รูปบุคลากร<input type="url" value={form.photoUrl} onChange={e=>set('photoUrl',e.target.value)} placeholder="ลิงก์รูปภาพจาก Google Drive"/></label><label>ตำแหน่ง<input disabled value={profile.position||''}/></label><div className="missing"><b>ข้อมูลที่ยังขาด</b><span>{profile.missing||'ไม่มี — ข้อมูลครบถ้วนแล้ว'}</span></div><button disabled={busy} className="primary save"><Save/>{busy?'กำลังบันทึก…':'บันทึกข้อมูลของฉัน'}</button></form></section>}
function WorkModal({onClose}){return <div className="back"><form onSubmit={e=>{e.preventDefault();onClose();Swal.fire({icon:'success',title:'บันทึกผลงานเรียบร้อยแล้ว',confirmButtonColor:'#d82f75'})}}><button type="button" className="x" onClick={onClose}><X/></button><Plus className="big"/><h2>เพิ่มผลงานใหม่</h2><p>บันทึกครั้งเดียว แล้วเชื่อมกับตัวชี้วัดได้หลายรายการ</p><label>ชื่อผลงาน<input required placeholder="ระบุชื่อโครงการ ผลงาน หรือกิจกรรม"/></label><div className="formgrid"><label>หมวดผลงาน<select><option>งานบริหารและงานประจำ</option><option>บริการวิชาการ</option><option>นวัตกรรมและเทคโนโลยี</option></select></label><label>วันที่ดำเนินการ<input type="date" defaultValue="2026-07-21"/></label></div><label>รายละเอียด<textarea placeholder="สรุปผลลัพธ์หรือบทบาทหน้าที่"/></label><div className="upload"><Upload/><b>ลากไฟล์มาวาง หรือเลือกจากอุปกรณ์</b><small>PDF, Word, Excel, รูปภาพ หรือวิดีโอ</small></div><button className="primary submit">บันทึกและเพิ่มหลักฐาน</button></form></div>}
function Card({icon,title,value,sub}){return <article className="card"><span>{icon}</span><p><small>{title}</small><b>{value}</b><em>{sub}</em></p></article>}function Head({title,sub}){return <div className="head"><div><h2>{title}</h2><p>{sub}</p></div></div>}function Module({active}){return <section className="module"><div className="stats"><Card icon={<CheckCircle2/>} title="ข้อมูลครบถ้วน" value="42" sub="รายการ"/><Card icon={<Clock3/>} title="กำลังดำเนินการ" value="6" sub="รายการ"/><Card icon={<ClipboardCheck/>} title="รอตรวจรับรอง" value="3" sub="รายการ"/></div><div className="panel auth-card"><Settings/><h2>{active}</h2><p>โมดูลพร้อมเชื่อมต่อฐานข้อมูลในลำดับถัดไป</p></div></section>}
const publicSlug=new URLSearchParams(location.search).get('portfolio');
createRoot(document.getElementById('root')).render(publicSlug?<PublicPortfolio api={api} slug={publicSlug}/>:<App/>);
