import React,{useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{LayoutDashboard,FolderOpen,ClipboardCheck,FileText,Users,BarChart3,Settings,Search,Plus,Share2,Bell,CheckCircle2,Clock3,BookOpen,FlaskConical,Handshake,Landmark,Sparkles,Upload,Download,Menu,X}from'lucide-react';import'./style.css';

const MCU_LOGO='https://lh3.googleusercontent.com/d/1d-tY28Km9oqKthhgl1s78aTrFa-gsYrP';
const people=[{name:'พระเมธีวัชราจารย์, ดร.',role:'ผู้อำนวยการหน่วยวิทยบริการฯ',initial:'ม'},{name:'พระครูสุธีสารบัณฑิต, ผศ.ดร.',role:'รองผู้อำนวยการฝ่ายวิชาการ',initial:'ส'},{name:'พระมหาธงชัย วิลาสินี',role:'นักวิชาการศึกษา · ผู้ดูแลระบบ',initial:'ธ'}];
const works=[['พัฒนาระบบตอบรับพิธีมอบประกาศนียบัตร ป.บส.','บริหารและงานประจำ','รับรองแล้ว',100],['โครงการอบรมพระนักเทศน์ Kalasin NextGen รุ่นที่ 2','บริการวิชาการ','รอตรวจ',82],['ระบบประเมินผลโครงการแบบออนไลน์','นวัตกรรมและเทคโนโลยี','รับรองแล้ว',100],['รายงานผลการปฏิบัติงาน ไตรมาส 3','รายงานและ SAR','ฉบับร่าง',46]];
const cats=[[BookOpen,'การจัดการเรียนการสอน',8,80],[FlaskConical,'วิจัยและวิชาการ',3,60],[Handshake,'บริการวิชาการ',12,92],[Landmark,'ทำนุบำรุงพระพุทธศาสนา',9,88],[ClipboardCheck,'บริหารและงานประจำ',16,100],[Sparkles,'พัฒนาตนเอง',6,75]];
const nav=[[LayoutDashboard,'ภาพรวม'],[FolderOpen,'แฟ้มผลงาน'],[ClipboardCheck,'รอบประเมิน'],[FileText,'รายงาน SAR'],[CheckCircle2,'กรรมการประเมิน'],[Users,'บุคลากร'],[BarChart3,'รายงาน']];
function App(){const[active,setActive]=useState('ภาพรวม'),[q,setQ]=useState(''),[modal,setModal]=useState(false),[mobile,setMobile]=useState(false),[toast,setToast]=useState('');const filtered=useMemo(()=>works.filter(w=>(w[0]+w[1]).includes(q)),[q]);const note=t=>{setToast(t);setTimeout(()=>setToast(''),2200)};return <div className="app">
<aside className={mobile?'side open':'side'}><div className="brand"><img src={MCU_LOGO}/><div><b>Smart Portfolio</b><small>MCU KALASIN</small></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div><div className="ready">● ระบบพร้อมใช้งาน</div><p className="label">พื้นที่ทำงาน</p><nav>{nav.map(([I,n])=><button className={active===n?'on':''} onClick={()=>{setActive(n);setMobile(false)}}><I/>{n}{n==='กรรมการประเมิน'&&<em>3</em>}</button>)}</nav><p className="label">ระบบ</p><nav><button><Settings/>ตั้งค่าระบบ</button></nav><div className="progress-card"><div>84%</div><p><b>แฟ้มของคุณ</b><small>เหลืออีก 4 รายการ</small></p></div><div className="profile"><span>ธ</span><p><b>พระมหาธงชัย วิลาสินี</b><small>นักวิชาการศึกษา</small></p></div></aside>
<main><header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหาผลงาน เอกสาร หรือบุคลากร..."/></div><button className="bell"><Bell/></button><div className="avatar">ธ</div></header><div className="content">
<section className="welcome"><div><small>แฟ้มสะสมผลงานดิจิทัล</small><h1>{active==='ภาพรวม'?'สวัสดีครับ, พระมหาธงชัย 👋':active}</h1><p>{active==='ภาพรวม'?'ภาพรวมผลงานและความก้าวหน้าในรอบ ปีงบประมาณ 2569':'จัดการข้อมูลและติดตามผลอย่างเป็นระบบ'}</p></div><div><button onClick={()=>note('สร้างลิงก์ Portfolio แล้ว')}><Share2/>แชร์ Portfolio</button><button className="primary" onClick={()=>setModal(true)}><Plus/>เพิ่มผลงานใหม่</button></div></section>
{active==='ภาพรวม'?<><section className="stats"><Card icon={<FolderOpen/>} title="ผลงานทั้งหมด" value="54" sub="12 รายการในรอบนี้"/><Card icon={<Clock3/>} title="รอการประเมิน" value="6" sub="ส่งตรวจล่าสุด 2 วันก่อน"/><Card icon={<CheckCircle2/>} title="รับรองแล้ว" value="42" sub="78% ของผลงานทั้งหมด"/><Card icon={<BarChart3/>} title="ความครบถ้วน" value="84%" sub="ครบแล้ว 16 จาก 20 ตัวชี้วัด"/></section><section className="columns"><div className="panel"><Head title="ความครบถ้วนตามพันธกิจ" sub="สรุปหลักฐานในแต่ละหมวดงาน"/><div className="cats">{cats.map(([I,n,c,p])=><article><div><I/><small>{c} ผลงาน</small></div><b>{n}</b><i><span style={{width:p+'%'}}/></i><small>{p}% ครบถ้วน</small></article>)}</div></div><div className="panel deadline"><Head title="กำหนดการสำคัญ" sub="รอบประเมินปัจจุบัน"/><div className="date"><b>30</b><span>ก.ย.</span><p><b>ส่งรายงานผลการปฏิบัติงาน</b><small>เหลือเวลา 71 วัน</small></p></div>{['เปิดรอบประเมิน','บันทึกข้อตกลงการปฏิบัติงาน','รวบรวมและส่งหลักฐาน','กรรมการตรวจประเมิน'].map((x,i)=><div className={i<2?'step done':i===2?'step current':'step'}><i>{i<2?'✓':i+1}</i><p><b>{x}</b><small>{i===2?'กำลังดำเนินการ':'ปีงบประมาณ 2569'}</small></p></div>)}</div></section></>:<Module active={active} people={people}/>}<section className="panel table"><Head title="ผลงานล่าสุด" sub="รายการที่เพิ่มและแก้ไขล่าสุด"/>{filtered.map((w,i)=><div className="row"><span className="file"><FileText/></span><p><b>{w[0]}</b><small>{w[1]} · {i+12} ก.ค. 2569</small></p><em className={w[2]}>{w[2]}</em><div className="bar"><span style={{width:w[3]+'%'}}/></div><b>{w[3]}%</b></div>)}</section></div></main>
{modal&&<div className="back"><form onSubmit={e=>{e.preventDefault();setModal(false);note('บันทึกผลงานเรียบร้อยแล้ว')}}><button type="button" className="x" onClick={()=>setModal(false)}><X/></button><Plus className="big"/><h2>เพิ่มผลงานใหม่</h2><p>บันทึกครั้งเดียว แล้วเชื่อมกับตัวชี้วัดได้หลายรายการ</p><label>ชื่อผลงาน<input required placeholder="ระบุชื่อโครงการ ผลงาน หรือกิจกรรม"/></label><div className="formgrid"><label>หมวดผลงาน<select><option>งานบริหารและงานประจำ</option><option>บริการวิชาการ</option><option>นวัตกรรมและเทคโนโลยี</option></select></label><label>วันที่ดำเนินการ<input type="date" defaultValue="2026-07-21"/></label></div><label>รายละเอียด<textarea placeholder="สรุปผลลัพธ์หรือบทบาทหน้าที่"/></label><div className="upload"><Upload/><b>ลากไฟล์มาวาง หรือเลือกจากอุปกรณ์</b><small>PDF, Word, Excel, รูปภาพ หรือวิดีโอ</small></div><button className="primary submit">บันทึกและเพิ่มหลักฐาน</button></form></div>}{toast&&<div className="toast">✓ {toast}</div>}</div>}
function Card({icon,title,value,sub}){return <article className="card"><span>{icon}</span><p><small>{title}</small><b>{value}</b><em>{sub}</em></p></article>}function Head({title,sub}){return <div className="head"><div><h2>{title}</h2><p>{sub}</p></div></div>}function Module({active,people}){return <section className="module"><div className="stats"><Card icon={<CheckCircle2/>} title="ข้อมูลครบถ้วน" value="42" sub="รายการ"/><Card icon={<Clock3/>} title="กำลังดำเนินการ" value="6" sub="รายการ"/><Card icon={<ClipboardCheck/>} title="รอตรวจรับรอง" value="3" sub="รายการ"/></div>{active==='บุคลากร'&&<div className="panel people"><Head title="ทำเนียบบุคลากร" sub="ข้อมูลกลางสำหรับแฟ้มสะสมผลงาน"/>{people.map(p=><article><span>{p.initial}</span><p><b>{p.name}</b><small>{p.role}</small></p><button>ดู Portfolio</button></article>)}</div>}</section>};createRoot(document.getElementById('root')).render(<App/>);
