import React,{useEffect,useMemo,useState}from'react';
import Swal from'sweetalert2';
import{ArchiveRestore,CheckCircle2,ClipboardCheck,CloudUpload,ExternalLink,Eye,FilePlus2,FileText,FolderOpen,Globe2,History,Link,Lock,MessageSquare,RefreshCw,RotateCcw,Search,Send,Star,Trash2,Upload,UserPlus,X}from'lucide-react';

const GOOGLE_CLIENT_ID=import.meta.env.VITE_GOOGLE_CLIENT_ID||'';
function googleDriveToken(){return new Promise(async(resolve,reject)=>{try{const cached=JSON.parse(sessionStorage.getItem('mcu_drive_token')||'null');if(cached?.token&&cached.expires>Date.now())return resolve(cached.token);if(!GOOGLE_CLIENT_ID)throw new Error('ยังไม่ได้กำหนด Google Client ID');if(!window.google?.accounts?.oauth2){await new Promise((ok,no)=>{const existing=document.querySelector('script[data-gsi]');if(existing){existing.addEventListener('load',ok,{once:true});existing.addEventListener('error',no,{once:true});return}const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.dataset.gsi='1';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}const client=window.google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CLIENT_ID,scope:'openid email https://www.googleapis.com/auth/drive',include_granted_scopes:true,callback:r=>{if(r.error)return reject(new Error(r.error_description||r.error));sessionStorage.setItem('mcu_drive_token',JSON.stringify({token:r.access_token,expires:Date.now()+Math.max(60,(Number(r.expires_in)||3600)-300)*1000}));resolve(r.access_token)},error_callback:e=>reject(new Error(e.message||'ผู้ใช้ยกเลิกการอนุญาต Google Drive'))});client.requestAccessToken({prompt:'consent'})}catch(e){reject(e)}})}

export default function PortfolioSuite({active,session,api,profile,isAdmin}){
 const[data,setData]=useState(null),[busy,setBusy]=useState(false),[modal,setModal]=useState(''),[selected,setSelected]=useState(null),[q,setQ]=useState('');
 const load=async()=>{if(!session?.token)return;setBusy(true);try{setData(await api({action:'portfolioHome',token:session.token}))}catch(e){Swal.fire({icon:'error',title:'โหลดข้อมูลไม่สำเร็จ',text:e.message})}finally{setBusy(false)}};
 useEffect(()=>{load()},[session?.token]);
 const act=async(action,payload,success)=>{setBusy(true);try{const r=await api({action,token:session.token,payload});if(r.works)setData(r);setModal('');await Swal.fire({icon:'success',title:success,confirmButtonColor:'#d82f75'});return r}catch(e){Swal.fire({icon:'error',title:'ดำเนินการไม่สำเร็จ',text:e.message,confirmButtonColor:'#d82f75'});throw e}finally{setBusy(false)}};
 const timeline=async work=>{setBusy(true);try{const r=await api({action:'workTimeline',token:session.token,payload:{workId:work.workId}}),rows=r.rows||[];await Swal.fire({title:`ประวัติ ${work.workId}`,width:820,html:`<div class="timeline-dialog">${rows.length?rows.map(x=>`<article><b>${x.action||'กิจกรรม'}</b><p>${x.details||x.newValue||''}</p><small>${x.timestamp||''} · ${x.userEmail||''}</small></article>`).join(''):'<p>ยังไม่มีประวัติเพิ่มเติม</p>'}</div>`,confirmButtonText:'ปิด',confirmButtonColor:'#d82f75'})}catch(e){Swal.fire({icon:'error',title:'เปิดประวัติไม่สำเร็จ',text:e.message})}finally{setBusy(false)}};
 if(!session)return <Empty icon={<Lock/>} title="กรุณาเข้าสู่ระบบ" text="เข้าสู่ระบบด้วย Google เพื่อใช้งานแฟ้มผลงานและการประเมิน"/>;
 if(active==='แฟ้มผลงาน')return <Works data={data} q={q} setQ={setQ} busy={busy} profile={profile} onReload={load} onAdd={()=>setModal('work')} onEvidence={w=>{setSelected(w);setModal('evidence')}} onTimeline={timeline} onState={(workId,state)=>act('setWorkState',{workId,state},state==='TRASH'?'ย้ายไปถังขยะแล้ว':state==='SUBMITTED'?'ส่งผลงานให้กรรมการแล้ว':state==='DRAFT'?'นำผลงานกลับมาแก้ไขแล้ว':state==='PUBLIC'?'เผยแพร่ Portfolio แล้ว':'อัปเดตผลงานแล้ว')}>{modal==='work'&&<WorkForm busy={busy} onClose={()=>setModal('')} onSubmit={p=>act('createWork',p,'เพิ่มผลงานแล้ว')}/>} {modal==='evidence'&&<EvidenceForm busy={busy} work={selected} onClose={()=>setModal('')} onLink={p=>act('addEvidenceLink',p,'เพิ่มหลักฐานแล้ว')} onUpload={async p=>{const driveAccessToken=await googleDriveToken();return act('uploadEvidence',{...p,driveAccessToken},'อัปโหลดหลักฐานขึ้น Google Drive แล้ว')}}/>}</Works>;
 if(active==='รอบประเมิน'||active==='รายงาน SAR')return <Assessment data={data} active={active}/>;
 if(active==='กรรมการประเมิน')return <ReviewCenter session={session} api={api} busy={busy} setBusy={setBusy} isAdmin={isAdmin}/>;
 if(active==='รายงาน')return <Reports data={data} profile={profile}/>;
 return <Empty icon={<FolderOpen/>} title={active} text="โมดูลพร้อมใช้งานและเชื่อมกับฐานข้อมูลกลาง"/>;
}

function Works({data,q,setQ,busy,profile,onReload,onAdd,onEvidence,onTimeline,onState,children}){
 const[filter,setFilter]=useState('ALL'),[sort,setSort]=useState('NEWEST');
 const all=data?.works||[],evidence=data?.evidence||[],matches=all.filter(w=>String(w['ชื่อผลงาน']||'').includes(q)),trash=matches.filter(w=>String(w['สถานะ']).toUpperCase()==='TRASH');
 const rows=matches.filter(w=>String(w['สถานะ']).toUpperCase()!=='TRASH').filter(w=>filter==='ALL'||String(w['สถานะ']||'DRAFT').toUpperCase()===filter).sort((a,b)=>sort==='NAME'?String(a['ชื่อผลงาน']).localeCompare(String(b['ชื่อผลงาน']),'th'):String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||'')));
 const confirmState=async(w,state)=>{if(['TRASH','SUBMITTED'].includes(state)){const c=await Swal.fire({icon:'question',title:state==='SUBMITTED'?'ส่งผลงานให้กรรมการตรวจ?':'ย้ายผลงานไปถังขยะ?',text:state==='SUBMITTED'?'หลังส่งตรวจ กรรมการจะเห็นหลักฐานทั้งหมดของผลงานนี้':'สามารถกู้คืนได้ภายหลัง',showCancelButton:true,confirmButtonText:'ยืนยัน',cancelButtonText:'ยกเลิก',confirmButtonColor:'#d82f75'});if(!c.isConfirmed)return}onState(w.workId,state)};
 return <section className="suite"><div className="suite-toolbar"><div><h2>แฟ้มผลงานของฉัน</h2><p>จัดเก็บหลักฐาน ส่งตรวจ ติดตามผล และเผยแพร่จากหน้าเดียว</p></div><div><button onClick={onReload}><RefreshCw/>รีเฟรช</button><button className="primary" onClick={onAdd}><FilePlus2/>เพิ่มผลงาน</button></div></div><div className="suite-stats"><Mini label="ผลงานทั้งหมด" value={data?.summary?.total||0}/><Mini label="เผยแพร่" value={data?.summary?.published||0}/><Mini label="รอประเมิน" value={data?.summary?.pending||0}/><Mini label="ถังขยะ" value={data?.summary?.trash||0}/></div><div className="panel suite-panel"><div className="suite-search suite-filters"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหาผลงาน"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">ทุกสถานะ</option><option value="DRAFT">ฉบับร่าง</option><option value="SUBMITTED">ส่งตรวจแล้ว</option><option value="REVISION">ขอแก้ไข</option><option value="APPROVED">รับรองแล้ว</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="NEWEST">แก้ไขล่าสุด</option><option value="NAME">เรียงตามชื่อ</option></select></div><div className="work-grid">{rows.map(w=>{const state=String(w['สถานะ']||'DRAFT').toUpperCase(),files=evidence.filter(e=>e.workId===w.workId&&String(e['สถานะ']).toUpperCase()!=='TRASH');return <article key={w.workId}><header><span><FileText/></span><em>{state}</em></header><h3>{w['ชื่อผลงาน']}</h3><p>{w['หมวดผลงาน']||'ยังไม่ระบุหมวด'} · {w['รอบประเมิน']||'ยังไม่เลือกรอบ'}</p><small className="evidence-count">{files.length} หลักฐาน</small>{files.length>0&&<details><summary>ดูหลักฐาน</summary>{files.map(f=><a key={f.evidenceId} href={f.driveUrl} target="_blank"><ExternalLink/>{f['ชื่อหลักฐาน']}</a>)}</details>}<div className="work-actions"><button onClick={()=>onEvidence(w)}><CloudUpload/>หลักฐาน</button>{['DRAFT','REVISION'].includes(state)&&<button className="accent" onClick={()=>confirmState(w,'SUBMITTED')}><Send/>ส่งตรวจ</button>}{state==='SUBMITTED'&&<button onClick={()=>onState(w.workId,'DRAFT')}><RotateCcw/>ถอนกลับ</button>}<button onClick={()=>onTimeline(w)}><History/>ประวัติ</button><button onClick={()=>onState(w.workId,String(w.visibility).toUpperCase()==='PUBLIC'?'PRIVATE':'PUBLIC')}>{String(w.visibility).toUpperCase()==='PUBLIC'?<><Lock/>ซ่อน</>:<><Globe2/>เผยแพร่</>}</button><button className="danger" onClick={()=>confirmState(w,'TRASH')}><Trash2/>ถังขยะ</button></div></article>})}{!rows.length&&<Empty icon={<FolderOpen/>} title="ไม่พบผลงาน" text="ลองเปลี่ยนตัวกรอง หรือกดเพิ่มผลงานใหม่"/>}</div></div>{trash.length>0&&<div className="panel trash-panel"><h3><Trash2/>ถังขยะ</h3>{trash.map(w=><div key={w.workId}><span>{w['ชื่อผลงาน']}</span><button onClick={()=>onState(w.workId,'DRAFT')}><ArchiveRestore/>กู้คืน</button></div>)}</div>}<PublicCard profile={profile}/>{busy&&<div className="suite-loading">กำลังประมวลผล…</div>}{children}</section>
}
function WorkForm({busy,onClose,onSubmit}){let defaultVisibility='PRIVATE';try{defaultVisibility=JSON.parse(localStorage.getItem('mcu_preferences')||'{}').defaultVisibility||'PRIVATE'}catch{}const[f,setF]=useState({name:'',category:'บริหารและงานประจำ',startDate:'',endDate:'',description:'',round:'',visibility:defaultVisibility,submit:false});const set=(k,v)=>setF(x=>({...x,[k]:v}));return <div className="back suite-back"><form className="suite-modal" onSubmit={e=>{e.preventDefault();onSubmit(f)}}><button type="button" className="x" onClick={onClose}><X/></button><FilePlus2 className="big"/><h2>เพิ่มผลงานใหม่</h2><label>ชื่อผลงาน<input required value={f.name} onChange={e=>set('name',e.target.value)}/></label><div className="formgrid"><label>หมวดผลงาน<select value={f.category} onChange={e=>set('category',e.target.value)}><option>การจัดการเรียนการสอน</option><option>วิจัยและวิชาการ</option><option>บริการวิชาการ</option><option>ทำนุบำรุงพระพุทธศาสนา</option><option>บริหารและงานประจำ</option><option>พัฒนาตนเอง</option></select></label><label>รอบประเมิน<input value={f.round} onChange={e=>set('round',e.target.value)} placeholder="เช่น PA 2569"/></label></div><div className="formgrid"><label>วันที่เริ่ม<input type="date" value={f.startDate} onChange={e=>set('startDate',e.target.value)}/></label><label>วันที่สิ้นสุด<input type="date" value={f.endDate} onChange={e=>set('endDate',e.target.value)}/></label></div><label>รายละเอียด/ผลลัพธ์<textarea value={f.description} onChange={e=>set('description',e.target.value)}/></label><div className="formgrid"><label>การเผยแพร่<select value={f.visibility} onChange={e=>set('visibility',e.target.value)}><option value="PRIVATE">เฉพาะฉันและกรรมการ</option><option value="PUBLIC">เผยแพร่ใน Portfolio</option></select></label><label className="check"><input type="checkbox" checked={f.submit} onChange={e=>set('submit',e.target.checked)}/>ส่งเข้ารอบประเมินทันที</label></div><button disabled={busy} className="primary submit"><FilePlus2/>{busy?'กำลังบันทึก…':'บันทึกผลงาน'}</button></form></div>}
function EvidenceForm({busy,work,onClose,onLink,onUpload}){const[name,setName]=useState(''),[url,setUrl]=useState(''),[file,setFile]=useState(null);const submit=async e=>{e.preventDefault();if(file){const data=await toData(file);return onUpload({workId:work.workId,name:name||file.name,fileName:file.name,data})}return onLink({workId:work.workId,name:name||'หลักฐานประกอบ',url})};return <div className="back suite-back"><form className="suite-modal" onSubmit={submit}><button type="button" className="x" onClick={onClose}><X/></button><Upload className="big"/><h2>เพิ่มหลักฐาน</h2><p>{work?.['ชื่อผลงาน']}</p><label>ชื่อหลักฐาน<input value={name} onChange={e=>setName(e.target.value)}/></label><label>ลิงก์ Google Drive หรือเว็บไซต์<input type="url" disabled={!!file} value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..."/></label><div className="or">หรือ</div><label className="file-drop"><CloudUpload/><b>{file?file.name:'เลือกไฟล์จากอุปกรณ์'}</b><small>สูงสุด 8 MB — บันทึกเข้า Google Drive</small><input type="file" onChange={e=>setFile(e.target.files[0]||null)}/></label><button disabled={busy||(!url&&!file)} className="primary submit"><Upload/>{busy?'กำลังอัปโหลด…':'เพิ่มหลักฐาน'}</button></form></div>}
function Assessment({data,active}){const rounds=data?.rounds||[],reviews=data?.reviews||[];return <section className="suite"><div className="suite-toolbar"><div><h2>{active}</h2><p>ติดตามความครบถ้วน กำหนดส่ง และผลการประเมินจากข้อมูลจริง</p></div></div><div className="suite-stats"><Mini label="รอบประเมิน" value={rounds.length}/><Mini label="ส่งตรวจแล้ว" value={(data?.works||[]).filter(w=>w['สถานะ']==='SUBMITTED').length}/><Mini label="ผลประเมิน" value={reviews.length}/><Mini label="ความครบถ้วน" value={`${Math.min(100,(data?.summary?.total||0)*5)}%`}/></div><div className="panel round-list"><h3><ClipboardCheck/>รอบประเมินปัจจุบัน</h3>{rounds.map(r=><article key={r.roundId}><div><b>{r['ชื่อรอบประเมิน']}</b><small>{r['ประเภท']} · ปิดส่ง {r['วันปิดส่งหลักฐาน']||'รอกำหนด'}</small></div><em>{r['สถานะ']}</em></article>)}{!rounds.length&&<p className="muted">ยังไม่มีรอบประเมินในชีต EvaluationRounds</p>}</div></section>}
function ReviewCenter({session,api,busy,setBusy}){const[d,setD]=useState(null);const load=async()=>{setBusy(true);try{setD(await api({action:'reviewerQueue',token:session.token}))}catch(e){Swal.fire({icon:'error',title:'เปิดคิวประเมินไม่ได้',text:e.message})}finally{setBusy(false)}};useEffect(()=>{load()},[]);return <section className="suite"><div className="suite-toolbar"><div><h2>ศูนย์กรรมการประเมิน</h2><p>ตรวจผลงาน ให้คะแนน ขอแก้ไข และรับรองผล</p></div><button onClick={load}><RefreshCw/>รีเฟรช</button></div><div className="panel review-list">{(d?.reviews||[]).map(r=><ReviewRow key={r.reviewId} row={r} busy={busy} onSave={async payload=>{setBusy(true);try{setD(await api({action:'saveReview',token:session.token,payload}));Swal.fire({icon:'success',title:'บันทึกผลประเมินแล้ว'})}finally{setBusy(false)}}}/>) }{!d?.reviews?.length&&<Empty icon={<ClipboardCheck/>} title="ยังไม่มีงานที่มอบหมาย" text="ผู้ดูแลสามารถเพิ่มรายการในชีต Reviews ได้"/>}</div></section>}
function ReviewRow({row,onSave,busy}){const[score,setScore]=useState(row['คะแนนรวม']||''),[comment,setComment]=useState(row['ข้อเสนอแนะ']||'');return <article><div><b>{row.personId} · {row.roundId}</b><small>{row['สถานะ']||'รอประเมิน'}</small></div><input type="number" min="0" max="100" value={score} onChange={e=>setScore(e.target.value)} placeholder="คะแนน"/><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="ข้อเสนอแนะ"/><button disabled={busy} onClick={()=>onSave({reviewId:row.reviewId,score,comment,status:'ประเมินแล้ว'})}><CheckCircle2/>รับรอง</button><button disabled={busy} onClick={()=>onSave({reviewId:row.reviewId,score,comment,status:'ขอแก้ไข'})}><RotateCcw/>ขอแก้ไข</button></article>}
function Reports({data,profile}){const works=data?.works||[],cats=Object.entries(works.reduce((a,w)=>(a[w['หมวดผลงาน']||'ไม่ระบุ']=(a[w['หมวดผลงาน']||'ไม่ระบุ']||0)+1,a),{}));return <section className="suite"><div className="suite-toolbar"><div><h2>รายงานและสรุปผล</h2><p>สรุปจากแฟ้มผลงานจริงของ {profile?.name||'ผู้ใช้งาน'}</p></div><button onClick={()=>window.print()}><FileText/>พิมพ์/PDF</button></div><div className="panel report-card"><h3>สรุปผลงานตามพันธกิจ</h3>{cats.map(([n,c])=><div key={n}><span>{n}</span><i><b style={{width:`${Math.min(100,c*10)}%`}}/></i><strong>{c} ผลงาน</strong></div>)}{!cats.length&&<p className="muted">ยังไม่มีข้อมูลผลงาน</p>}</div></section>}
function PublicCard({profile}){const slug=profile?.portfolioSlug||profile?.personId?.toLowerCase();if(!slug)return null;const url=`${location.origin}/?portfolio=${encodeURIComponent(slug)}`;return <div className="panel public-card"><Globe2/><div><h3>Portfolio สาธารณะ</h3><p>{url}</p></div><button onClick={()=>navigator.clipboard.writeText(url).then(()=>Swal.fire({icon:'success',title:'คัดลอกลิงก์แล้ว'}))}><Link/>คัดลอก</button><a href={url} target="_blank"><ExternalLink/>เปิดดู</a></div>}
function Mini({label,value}){return <article><small>{label}</small><b>{value}</b></article>}
function Empty({icon,title,text}){return <div className="suite-empty">{icon}<h3>{title}</h3><p>{text}</p></div>}
function toData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}

export function PublicPortfolio({api,slug}){const[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{api({action:'publicPortfolio',slug}).then(setData).catch(e=>setError(e.message))},[slug]);if(error)return <div className="public-page"><Empty icon={<Globe2/>} title="ไม่พบ Portfolio" text={error}/></div>;if(!data)return <div className="public-page"><div className="suite-loading">กำลังเปิด Portfolio…</div></div>;return <main className="public-page"><header><div><small>MCU KALASIN SMART PORTFOLIO</small><h1>{data.profile.prefix} {data.profile.name}</h1><p>{data.profile.position} · {data.profile.department}</p></div>{data.profile.photoUrl&&<img src={data.profile.photoUrl}/>}</header><section><h2>ผลงานที่เผยแพร่</h2><div className="work-grid">{data.works.map(w=><article key={w.workId}><header><span><Star/></span><em>{w['หมวดผลงาน']}</em></header><h3>{w['ชื่อผลงาน']}</h3><p>{w['รายละเอียด/ผลลัพธ์']}</p>{data.evidence.filter(e=>e.workId===w.workId).map(e=><a key={e.evidenceId} href={e.driveUrl} target="_blank"><ExternalLink/> {e['ชื่อหลักฐาน']}</a>)}</article>)}</div></section><footer>พัฒนาโดย พระมหาธงชัย วิลาสินี · หน่วยวิทยบริการ วิทยาลัยสงฆ์ขอนแก่น จังหวัดกาฬสินธุ์</footer></main>}
